#!/usr/bin/env python3
"""
==============================================================================
Project: ARES-RX Sentinel — Post-Silicon Validation Harness
Module:  rp2040_stimulus_generator.py
Target:  Raspberry Pi Pico / RP2040 PIO & Benchtop Logic Analyzer
Standard: Python 3.8+

Description:
  Generates calibrated physical timing stimulus patterns and PIO assembly
  programs for the RP2040 test controller. Supports generating nominal
  Manchester frames (20 kHz, 50 us/cycle), calibrated runt glitches,
  mid-band desynchronization pulses, and boundary timing sweeps.
==============================================================================
"""

import sys
import argparse
from typing import List, Tuple

# Timing constants @ 20 kHz nominal clock (T_clk = 50.0 us)
F_CLK_HZ = 20_000
T_CLK_US = 1_000_000.0 / F_CLK_HZ  # 50.0 us

# Discrete cycle bounds
N_HB_NOMINAL = 9      # 450 us
N_BIT_NOMINAL = 18    # 900 us
N_EOF_NOMINAL = 64    # 3200 us


def generate_manchester_bit(bit: int) -> List[Tuple[int, float]]:
    """
    Generate physical levels and durations for a single Manchester-encoded bit.
    Standard convention:
      Bit 0: Low for half-bit, High for half-bit
      Bit 1: High for half-bit, Low for half-bit
    """
    half_bit_us = N_HB_NOMINAL * T_CLK_US
    if bit == 0:
        return [(0, half_bit_us), (1, half_bit_us)]
    else:
        return [(1, half_bit_us), (0, half_bit_us)]


def generate_frame_transitions(hex_payload: str) -> List[Tuple[int, float]]:
    """
    Convert a 192-bit hex frame into a list of (level, duration_us) transitions.
    Includes lead-in arming preamble.
    """
    transitions: List[Tuple[int, float]] = []
    
    # 1. Lead-in arming pulses (2 nominal half-bit pulses to transition L1 IDLE -> ARMED -> ACTIVE)
    half_bit_us = N_HB_NOMINAL * T_CLK_US
    transitions.append((1, half_bit_us))
    transitions.append((0, half_bit_us))
    
    # 2. Convert hex string to binary bitstream
    val = int(hex_payload, 16)
    bit_str = f"{val:0192b}"
    
    # 3. Generate Manchester pulses
    for ch in bit_str:
        bit = int(ch)
        transitions.extend(generate_manchester_bit(bit))
        
    # 4. Trailing quiet period (EOP = 64 cycles = 3200 us)
    eop_us = N_EOF_NOMINAL * T_CLK_US
    transitions.append((0, eop_us))
    
    return transitions


def generate_runt_glitch_test() -> List[Tuple[int, float]]:
    """Generate a valid preamble followed by a 4-cycle runt glitch (<8 cycles)."""
    transitions = []
    half_bit_us = N_HB_NOMINAL * T_CLK_US
    # Arming
    transitions.append((1, half_bit_us))
    transitions.append((0, half_bit_us))
    
    # First 8 bits of preamble (0xAA)
    for b in [1, 0, 1, 0, 1, 0, 1, 0]:
        transitions.extend(generate_manchester_bit(b))
        
    # Inject 4-cycle runt pulse (200 us)
    runt_us = 4 * T_CLK_US
    transitions.append((1, runt_us))
    transitions.append((0, half_bit_us))
    
    return transitions


def export_csv(transitions: List[Tuple[int, float]], filename: str):
    """Export transitions to a CSV format readable by Saleae Logic or RP2040."""
    with open(filename, "w") as f:
        f.write("Time[s],Channel_rx_in\n")
        current_time = 0.0
        for level, dur_us in transitions:
            dur_s = dur_us / 1_000_000.0
            f.write(f"{current_time:.6f},{level}\n")
            current_time += dur_s
            f.write(f"{current_time:.6f},{level}\n")
    print(f"[+] Successfully exported {len(transitions)} transitions to {filename}")


def export_rp2040_c_header(filename: str):
    """Export C array definitions for embedding in RP2040 firmware."""
    nominal_hex = "AAAAAAAAAAAAAAAA" "D391" "D391" "0DFFFFFE" "12345678" "0015" "0018" "01" "000000"
    trans = generate_frame_transitions(nominal_hex)
    
    with open(filename, "w") as f:
        f.write("/* Auto-generated by rp2040_stimulus_generator.py */\n")
        f.write("#ifndef STIMULUS_VECTORS_H\n#define STIMULUS_VECTORS_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"// Total transitions: {len(trans)}\n")
        f.write("typedef struct { uint8_t level; uint16_t duration_us; } stimulus_pulse_t;\n\n")
        f.write(f"static const stimulus_pulse_t nominal_frame_stimulus[{len(trans)}] = {{\n")
        for lvl, dur in trans:
            f.write(f"    {{ {lvl}, {int(dur)} }},\n")
        f.write("};\n\n#endif // STIMULUS_VECTORS_H\n")
    print(f"[+] Successfully generated RP2040 firmware header: {filename}")


def main():
    parser = argparse.ArgumentParser(description="RP2040 Stimulus Generator for ARES-RX Sentinel")
    parser.add_argument("--csv", help="Export nominal frame to CSV", default="nominal_stimulus.csv")
    parser.add_argument("--runt-csv", help="Export runt glitch attack to CSV", default="runt_glitch_stimulus.csv")
    parser.add_argument("--header", help="Export RP2040 C header", default="stimulus_vectors.h")
    args = parser.parse_args()
    
    # Nominal frame
    nominal_hex = "AAAAAAAAAAAAAAAA" "D391" "D391" "0DFFFFFE" "12345678" "0015" "0018" "01" "000000"
    nom_trans = generate_frame_transitions(nominal_hex)
    export_csv(nom_trans, args.csv)
    
    # Runt glitch
    runt_trans = generate_runt_glitch_test()
    export_csv(runt_trans, args.runt_csv)
    
    # C header
    export_rp2040_c_header(args.header)


if __name__ == "__main__":
    main()
